import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { config } from './config.js';

const sb=createClient(config.SUPABASE_URL,config.SUPABASE_ANON_KEY); const app=document.querySelector('#app');
const state={session:null,view:'inicio',query:'',results:[],media:[],detail:null,loading:false};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const img=p=>p?`https://image.tmdb.org/t/p/w500${p}`:'assets/icons/icon.svg';
function toast(t){const n=document.createElement('div');n.className='toast';n.textContent=t;document.body.append(n);setTimeout(()=>n.remove(),3000)}
function nav(){return `<nav class="nav">${[['inicio','⌂ Inicio'],['buscar','⌕ Buscar'],['lista','▣ Mi lista'],['estadisticas','◒ Estadísticas'],['perfil','◎ Perfil']].map(([v,l])=>`<button class="${state.view===v?'active':''}" data-view="${v}">${l}</button>`).join('')}</nav>`}
function shell(content){app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><span class="logo-mark">T</span><strong>TrackTin</strong></div><div class="row"><span class="muted">${esc(state.session?.user?.email||'')}</span><button class="btn secondary" data-action="logout">Salir</button></div></header><div class="layout"><aside class="sidebar">${nav()}</aside><main>${content}</main></div><div class="bottomnav">${nav()}</div></div>`;bind();}
function auth(){app.innerHTML=`<section class="auth"><div class="auth-card"><div class="brand"><span class="logo-mark">T</span><strong>TrackTin</strong></div><h1>Tu próxima historia empieza aquí</h1><p class="muted">Sigue tus películas, series y episodios en un solo lugar.</p><form id="auth-form" class="card"><label>Correo<input class="input" type="email" name="email" required autocomplete="email"></label><br><label>Contraseña<input class="input" type="password" name="password" minlength="6" required autocomplete="current-password"></label><br><div class="row"><button class="btn" name="mode" value="login">Iniciar sesión</button><button class="btn secondary" name="mode" value="signup">Crear cuenta</button></div><button class="btn ghost" name="mode" value="reset" type="submit">Recuperar contraseña</button><p id="auth-msg" class="muted"></p></form></div></section>`;document.querySelector('#auth-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),email=f.get('email'),password=f.get('password'),mode=f.get('mode');let r=mode==='signup'?await sb.auth.signUp({email,password}):mode==='reset'?await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname}):await sb.auth.signInWithPassword({email,password});document.querySelector('#auth-msg').textContent=r.error?.message||(mode==='signup'?'Revisa tu correo para confirmar la cuenta.':'Listo.');};}
async function tmdb(path,params={}){const q=new URLSearchParams({path,...params});const r=await fetch(`${config.TMDB_PROXY_URL}?${q}`);if(!r.ok)throw Error('No se pudo consultar TMDB');return r.json()}
function posterCard(m){return `<article class="card media-card"><img class="poster" loading="lazy" src="${img(m.poster_path)}" alt="Carátula de ${esc(m.title||m.name)}"><div class="card-body"><h3>${esc(m.title||m.name)}</h3><p class="muted">${(m.release_date||m.first_air_date||'').slice(0,4)||'—'} · ${m.media_type==='tv'?'Serie':'Película'}</p><br><button class="btn" data-detail="${m.id}" data-type="${m.media_type||'movie'}">Ver ficha</button></div></article>`}
async function search(){state.loading=true;render();try{const d=await tmdb('/search/multi',{query:state.query,language:'es-ES',region:'ES',page:1});state.results=(d.results||[]).filter(x=>x.media_type==='movie'||x.media_type==='tv')}catch(e){toast(e.message)}state.loading=false;render();}
async function loadList(){const r=await sb.from('tracktin_media').select('*').order('updated_at',{ascending:false});if(r.error)toast('No se pudo cargar tu lista');state.media=r.data||[];}
async function detail(id,type){state.detail=await tmdb(`/${type}/${id}`,{language:'es-ES',region:'ES',append_to_response:'credits,videos,watch/providers'});state.detail.media_type=type;state.view='detalle';render();}
function home(){const recent=state.media.slice(0,6);return `<div class="hero"><div><span class="eyebrow">Tu sala personal</span><h1>¿Qué vemos hoy?</h1><p class="muted">Tu seguimiento, al día y sin spoilers.</p></div><button class="btn" data-view="buscar">Buscar títulos</button></div><section><h2>Tu lista reciente</h2>${recent.length?`<div class="grid">${recent.map(m=>posterCard({id:m.tmdb_id,media_type:m.media_type,title:`TMDB #${m.tmdb_id}`})).join('')}</div>`:'<div class="empty">Aún no tienes títulos. Busca una película o serie para empezar.</div>'}</section>`}
function searchPage(){return `<div class="hero"><div><span class="eyebrow">Explorar</span><h1>Buscar</h1><p class="muted">Películas y series de TMDB, en español.</p></div></div><form id="search-form" class="search"><input class="input" name="q" value="${esc(state.query)}" placeholder="Título, saga o serie…" aria-label="Buscar títulos"><button class="btn">Buscar</button></form><br>${state.loading?'<p class="muted">Buscando…</p>':state.results.length?`<div class="grid">${state.results.map(posterCard).join('')}</div>`:state.query?'<div class="empty">No hemos encontrado resultados.</div>':'<div class="empty">Escribe un título para empezar.</div>'}`}
function listPage(){return `<div class="hero"><div><span class="eyebrow">Colección</span><h1>Mi lista</h1></div></div><div class="row"><button class="btn secondary">Todo</button><button class="btn secondary">Pendientes</button><button class="btn secondary">Favoritos</button></div><br>${state.media.length?`<div class="grid">${state.media.map(m=>posterCard({id:m.tmdb_id,media_type:m.media_type,title:`TMDB #${m.tmdb_id}`})).join('')}</div>`:'<div class="empty">Tu lista está vacía.</div>'}`}
function detailPage(){const m=state.detail;return `<button class="btn ghost" data-view="buscar">← Volver</button><br><br><article class="detail-hero"><img class="detail-poster" src="${img(m.poster_path)}" alt="Carátula de ${esc(m.title||m.name)}"><div><span class="eyebrow">${m.media_type==='tv'?'Serie':'Película'}</span><h1>${esc(m.title||m.name)}</h1><p class="muted">${(m.release_date||m.first_air_date||'').slice(0,4)} · ${esc((m.genres||[]).map(g=>g.name).join(', '))}</p><p>${esc(m.overview||'Sinopsis no disponible.')}</p><div class="row"><button class="btn" data-save="${m.id}" data-type="${m.media_type}">Añadir a mi lista</button><button class="btn secondary" data-watched="${m.id}" data-type="${m.media_type}">Marcar como vista</button></div></div></article>${m.media_type==='tv'?'<h2>Temporadas</h2><div class="empty">Abre una temporada para cargar sus episodios. La estructura de progreso está preparada en Supabase.</div>':''}`}
function profile(){return `<div class="hero"><div><span class="eyebrow">Cuenta</span><h1>Perfil y ajustes</h1></div></div><div class="card"><p>Sesión iniciada como <strong>${esc(state.session.user.email)}</strong></p><p class="muted">Versión ${config.APP_VERSION}</p><p>TMDB se consulta mediante una Edge Function y tus datos personales están protegidos por RLS.</p></div>`}
function render(){if(!state.session)return auth();let c=state.view==='inicio'?home():state.view==='buscar'?searchPage():state.view==='lista'?listPage():state.view==='detalle'?detailPage():profile();shell(c)}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});document.querySelector('[data-action="logout"]')?.addEventListener('click',async()=>{await sb.auth.signOut();state.session=null;render()});document.querySelector('#search-form')?.addEventListener('submit',e=>{e.preventDefault();state.query=new FormData(e.currentTarget).get('q').trim();if(state.query)search()});document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail,b.dataset.type));document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>save(b.dataset.id,b.dataset.type));document.querySelectorAll('[data-watched]').forEach(b=>b.onclick=()=>save(b.dataset.id,b.dataset.type,'watched'));}
async function save(id,type,status='pending'){const r=await sb.from('tracktin_media').upsert({user_id:state.session.user.id,tmdb_id:Number(id),media_type:type,status,updated_at:new Date().toISOString()},{onConflict:'user_id,tmdb_id,media_type'});if(r.error)toast('No se pudo guardar el título');else{toast('Guardado en tu lista');await loadList();}}
sb.auth.onAuthStateChange((_e,s)=>{state.session=s;if(s)loadList().then(render);else render()});sb.auth.getSession().then(({data})=>{state.session=data.session;data.session?loadList().then(render):render()});if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
