-- Ejecutar en el SQL Editor del proyecto Supabase de Webs.
-- Las migraciones equivalentes viven en supabase/migrations/20260616090000_trastero.sql
-- y supabase/migrations/20260616110000_trastero_thumbnails.sql.

begin;

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles
    add constraint profiles_role_check check (role in ('admin', 'member', 'viewer', 'trastero'));

create or replace function public.can_access_trastero()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1 from public.profiles
        where id = auth.uid() and role in ('admin', 'trastero')
    );
$$;

grant execute on function public.can_access_trastero() to authenticated;

create or replace function public.trastero_set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create table if not exists public.trastero_zonas (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    nombre text not null,
    notas text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.trastero_cajas (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    zona_id bigint references public.trastero_zonas(id) on delete set null,
    ubicacion text,
    nombre text not null,
    notas text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.trastero_objetos (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    zona_id bigint references public.trastero_zonas(id) on delete set null,
    caja_id bigint references public.trastero_cajas(id) on delete set null,
    nombre text not null,
    notas text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.trastero_fotos (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    tipo text not null check (tipo in ('zona', 'caja', 'objeto')),
    relacion_id bigint not null,
    storage_path text not null unique,
    thumbnail_path text unique,
    created_at timestamptz not null default now()
);

alter table public.trastero_fotos
    add column if not exists thumbnail_path text;

create index if not exists trastero_zonas_user_id_idx on public.trastero_zonas(user_id);
create index if not exists trastero_cajas_user_id_idx on public.trastero_cajas(user_id);
create index if not exists trastero_cajas_zona_id_idx on public.trastero_cajas(zona_id);
create index if not exists trastero_objetos_user_id_idx on public.trastero_objetos(user_id);
create index if not exists trastero_objetos_zona_id_idx on public.trastero_objetos(zona_id);
create index if not exists trastero_objetos_caja_id_idx on public.trastero_objetos(caja_id);
create index if not exists trastero_fotos_user_id_idx on public.trastero_fotos(user_id);
create index if not exists trastero_fotos_tipo_relacion_idx on public.trastero_fotos(tipo, relacion_id);

drop trigger if exists trastero_zonas_updated_at on public.trastero_zonas;
create trigger trastero_zonas_updated_at before update on public.trastero_zonas
for each row execute function public.trastero_set_updated_at();
drop trigger if exists trastero_cajas_updated_at on public.trastero_cajas;
create trigger trastero_cajas_updated_at before update on public.trastero_cajas
for each row execute function public.trastero_set_updated_at();
drop trigger if exists trastero_objetos_updated_at on public.trastero_objetos;
create trigger trastero_objetos_updated_at before update on public.trastero_objetos
for each row execute function public.trastero_set_updated_at();

create or replace function public.trastero_validate_relations()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    if new.user_id <> auth.uid() then
        raise exception 'user_id no permitido';
    end if;
    if tg_table_name = 'trastero_cajas' and new.zona_id is not null
       and not exists (select 1 from public.trastero_zonas where id = new.zona_id and user_id = new.user_id) then
        raise exception 'Zona no permitida';
    end if;
    if tg_table_name = 'trastero_objetos' then
        if new.zona_id is not null and not exists (select 1 from public.trastero_zonas where id = new.zona_id and user_id = new.user_id) then
            raise exception 'Zona no permitida';
        end if;
        if new.caja_id is not null and not exists (select 1 from public.trastero_cajas where id = new.caja_id and user_id = new.user_id) then
            raise exception 'Caja no permitida';
        end if;
    end if;
    return new;
end;
$$;

drop trigger if exists trastero_cajas_validate_relations on public.trastero_cajas;
create trigger trastero_cajas_validate_relations before insert or update on public.trastero_cajas
for each row execute function public.trastero_validate_relations();
drop trigger if exists trastero_objetos_validate_relations on public.trastero_objetos;
create trigger trastero_objetos_validate_relations before insert or update on public.trastero_objetos
for each row execute function public.trastero_validate_relations();

create or replace function public.trastero_validate_photo()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    if new.user_id <> auth.uid() then raise exception 'user_id no permitido'; end if;
    if new.tipo = 'zona' and not exists (select 1 from public.trastero_zonas where id = new.relacion_id and user_id = new.user_id) then raise exception 'Zona no permitida'; end if;
    if new.tipo = 'caja' and not exists (select 1 from public.trastero_cajas where id = new.relacion_id and user_id = new.user_id) then raise exception 'Caja no permitida'; end if;
    if new.tipo = 'objeto' and not exists (select 1 from public.trastero_objetos where id = new.relacion_id and user_id = new.user_id) then raise exception 'Objeto no permitido'; end if;
    return new;
end;
$$;

drop trigger if exists trastero_fotos_validate on public.trastero_fotos;
create trigger trastero_fotos_validate before insert or update on public.trastero_fotos
for each row execute function public.trastero_validate_photo();

alter table public.trastero_zonas enable row level security;
alter table public.trastero_cajas enable row level security;
alter table public.trastero_objetos enable row level security;
alter table public.trastero_fotos enable row level security;

do $$
declare table_name text;
begin
    foreach table_name in array array['trastero_zonas', 'trastero_cajas', 'trastero_objetos', 'trastero_fotos']
    loop
        execute format('drop policy if exists "Trastero own rows" on public.%I', table_name);
        execute format(
            'create policy "Trastero own rows" on public.%I for all to authenticated using (public.can_access_trastero() and auth.uid() = user_id) with check (public.can_access_trastero() and auth.uid() = user_id)',
            table_name
        );
    end loop;
end $$;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('trastero-fotos', 'trastero-fotos', false, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif'])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Trastero users read own photos" on storage.objects;
create policy "Trastero users read own photos" on storage.objects for select to authenticated
using (bucket_id = 'trastero-fotos' and public.can_access_trastero() and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "Trastero users upload own photos" on storage.objects;
create policy "Trastero users upload own photos" on storage.objects for insert to authenticated
with check (bucket_id = 'trastero-fotos' and public.can_access_trastero() and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "Trastero users update own photos" on storage.objects;
create policy "Trastero users update own photos" on storage.objects for update to authenticated
using (bucket_id = 'trastero-fotos' and public.can_access_trastero() and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id = 'trastero-fotos' and public.can_access_trastero() and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "Trastero users delete own photos" on storage.objects;
create policy "Trastero users delete own photos" on storage.objects for delete to authenticated
using (bucket_id = 'trastero-fotos' and public.can_access_trastero() and (storage.foldername(name))[1] = auth.uid()::text);

insert into public.app_projects (slug, name, description)
values ('trastero', 'Trastero', 'Inventario privado de zonas, cajas y objetos.')
on conflict (slug) do update set name = excluded.name, description = excluded.description, is_active = true;

commit;
