begin;

create table if not exists public.trastero_espacios (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    nombre text not null,
    foto_path text unique,
    thumbnail_path text unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists trastero_espacios_user_id_idx on public.trastero_espacios(user_id);

drop trigger if exists trastero_espacios_updated_at on public.trastero_espacios;
create trigger trastero_espacios_updated_at before update on public.trastero_espacios
for each row execute function public.trastero_set_updated_at();

alter table public.trastero_espacios enable row level security;
drop policy if exists "Trastero own rows" on public.trastero_espacios;
create policy "Trastero own rows" on public.trastero_espacios
for all to authenticated
using (public.can_access_trastero() and auth.uid() = user_id)
with check (public.can_access_trastero() and auth.uid() = user_id);

alter table public.trastero_zonas add column if not exists espacio_id bigint references public.trastero_espacios(id) on delete cascade;
alter table public.trastero_cajas add column if not exists espacio_id bigint references public.trastero_espacios(id) on delete cascade;
alter table public.trastero_objetos add column if not exists espacio_id bigint references public.trastero_espacios(id) on delete cascade;

insert into public.trastero_espacios (user_id, nombre)
select user_id, 'Mi casa'
from (
    select user_id from public.trastero_zonas
    union
    select user_id from public.trastero_cajas
    union
    select user_id from public.trastero_objetos
) usuarios
where not exists (
    select 1 from public.trastero_espacios e
    where e.user_id = usuarios.user_id
);

with preferidos as (
    select distinct on (user_id) user_id, id
    from public.trastero_espacios
    order by user_id, id
)
update public.trastero_zonas z
set espacio_id = p.id
from preferidos p
where z.user_id = p.user_id and z.espacio_id is null;

with preferidos as (
    select distinct on (user_id) user_id, id
    from public.trastero_espacios
    order by user_id, id
)
update public.trastero_cajas c
set espacio_id = p.id
from preferidos p
where c.user_id = p.user_id and c.espacio_id is null;

with preferidos as (
    select distinct on (user_id) user_id, id
    from public.trastero_espacios
    order by user_id, id
)
update public.trastero_objetos o
set espacio_id = p.id
from preferidos p
where o.user_id = p.user_id and o.espacio_id is null;

alter table public.trastero_zonas alter column espacio_id set not null;
alter table public.trastero_cajas alter column espacio_id set not null;
alter table public.trastero_objetos alter column espacio_id set not null;

create index if not exists trastero_zonas_espacio_id_idx on public.trastero_zonas(espacio_id);
create index if not exists trastero_cajas_espacio_id_idx on public.trastero_cajas(espacio_id);
create index if not exists trastero_objetos_espacio_id_idx on public.trastero_objetos(espacio_id);

create or replace function public.trastero_validate_relations()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    if new.user_id <> auth.uid() then
        raise exception 'user_id no permitido';
    end if;
    if not exists (select 1 from public.trastero_espacios where id = new.espacio_id and user_id = new.user_id) then
        raise exception 'Espacio no permitido';
    end if;
    if tg_table_name = 'trastero_cajas' and new.zona_id is not null
       and not exists (select 1 from public.trastero_zonas where id = new.zona_id and user_id = new.user_id and espacio_id = new.espacio_id) then
        raise exception 'Zona no permitida';
    end if;
    if tg_table_name = 'trastero_objetos' then
        if new.zona_id is not null and not exists (select 1 from public.trastero_zonas where id = new.zona_id and user_id = new.user_id and espacio_id = new.espacio_id) then
            raise exception 'Zona no permitida';
        end if;
        if new.caja_id is not null and not exists (select 1 from public.trastero_cajas where id = new.caja_id and user_id = new.user_id and espacio_id = new.espacio_id) then
            raise exception 'Caja no permitida';
        end if;
    end if;
    return new;
end;
$$;

drop trigger if exists trastero_zonas_validate_relations on public.trastero_zonas;
create trigger trastero_zonas_validate_relations before insert or update on public.trastero_zonas
for each row execute function public.trastero_validate_relations();
drop trigger if exists trastero_cajas_validate_relations on public.trastero_cajas;
create trigger trastero_cajas_validate_relations before insert or update on public.trastero_cajas
for each row execute function public.trastero_validate_relations();
drop trigger if exists trastero_objetos_validate_relations on public.trastero_objetos;
create trigger trastero_objetos_validate_relations before insert or update on public.trastero_objetos
for each row execute function public.trastero_validate_relations();

commit;
