insert into public.app_projects (slug, name, description)
values ('bingo', 'bingo', 'Gestion del monitor y las partidas de Bingo.')
on conflict (slug) do update
set name = excluded.name,
    description = excluded.description,
    is_active = true,
    updated_at = now();

create or replace function public.can_manage_bingo()
returns boolean
language sql
security definer
set search_path = public
as $$
    select public.is_admin()
        or exists (
            select 1
            from public.project_members pm
            join public.app_projects ap on ap.id = pm.project_id
            where pm.user_id = auth.uid()
              and ap.slug = 'bingo'
              and ap.is_active
              and pm.role in ('owner', 'editor')
        );
$$;

create table if not exists public.bingo_partidas (
    id integer generated by default as identity (start with 100 increment by 1),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    iniciada boolean not null default false,
    primary key (id),
    constraint bingo_partidas_id_tres_cifras check (id between 100 and 999)
);

alter table public.bingo_partidas
    add column if not exists created_at timestamptz not null default now(),
    add column if not exists updated_at timestamptz not null default now(),
    add column if not exists iniciada boolean not null default false;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conrelid = 'public.bingo_partidas'::regclass
          and conname = 'bingo_partidas_id_tres_cifras'
    ) then
        alter table public.bingo_partidas
            add constraint bingo_partidas_id_tres_cifras check (id between 100 and 999);
    end if;
end;
$$;

do $$
declare
    sequence_name text;
begin
    sequence_name := pg_get_serial_sequence('public.bingo_partidas', 'id');

    if sequence_name is not null then
        execute format('alter sequence %s minvalue 100 maxvalue 999 no cycle', sequence_name);
        execute format('grant usage, select on sequence %s to authenticated', sequence_name);
    end if;
end;
$$;

alter table public.bingo_partidas enable row level security;

grant select on public.bingo_partidas to anon, authenticated;
grant insert, update, delete on public.bingo_partidas to authenticated;

drop policy if exists "Public can read bingo partidas" on public.bingo_partidas;
drop policy if exists "Bingo managers can insert partidas" on public.bingo_partidas;
drop policy if exists "Bingo managers can update partidas" on public.bingo_partidas;
drop policy if exists "Bingo managers can delete partidas" on public.bingo_partidas;

create policy "Public can read bingo partidas"
on public.bingo_partidas
for select
to anon, authenticated
using (true);

create policy "Bingo managers can insert partidas"
on public.bingo_partidas
for insert
to authenticated
with check (public.can_manage_bingo());

create policy "Bingo managers can update partidas"
on public.bingo_partidas
for update
to authenticated
using (public.can_manage_bingo())
with check (public.can_manage_bingo());

create policy "Bingo managers can delete partidas"
on public.bingo_partidas
for delete
to authenticated
using (public.can_manage_bingo());
