-- Amplía las tablas existentes sin alterar el flujo local/offline.
alter table public.infiltrado_partidas
    add column if not exists modo text not null default 'offline',
    add column if not exists codigo_publico text,
    add column if not exists estado_online text not null default 'waiting',
    add column if not exists started_at timestamptz,
    add column if not exists ended_at timestamptz;

alter table public.infiltrado_partidas
    alter column palabra_oculta set default '';

alter table public.infiltrado_partidas
    drop constraint if exists infiltrado_partidas_user_id_key;

create unique index if not exists infiltrado_partidas_codigo_publico_unique
on public.infiltrado_partidas (codigo_publico)
where codigo_publico is not null;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'infiltrado_partidas_codigo_publico_check'
          and conrelid = 'public.infiltrado_partidas'::regclass
    ) then
        alter table public.infiltrado_partidas
            add constraint infiltrado_partidas_codigo_publico_check
            check (codigo_publico is null or codigo_publico ~ '^[0-9]{3}$');
    end if;
end;
$$;

alter table public.infiltrado_jugadores
    add column if not exists player_token text,
    add column if not exists es_anfitrion boolean not null default false,
    add column if not exists last_seen_at timestamptz not null default now();

create unique index if not exists infiltrado_jugadores_partida_token_unique
on public.infiltrado_jugadores (partida_id, player_token)
where player_token is not null;

create table if not exists public.infiltrado_resultados (
    id bigint generated by default as identity primary key,
    partida_id uuid not null references public.infiltrado_partidas(id) on delete cascade,
    jugador_sospechoso_1 bigint references public.infiltrado_jugadores(id) on delete set null,
    jugador_sospechoso_2 bigint references public.infiltrado_jugadores(id) on delete set null,
    acierto boolean not null,
    created_at timestamptz not null default now()
);

create index if not exists infiltrado_resultados_partida_id_idx
on public.infiltrado_resultados (partida_id);

alter table public.infiltrado_resultados enable row level security;
grant select, insert, delete on public.infiltrado_resultados to authenticated;

do $$
declare
    sequence_name text;
begin
    sequence_name := pg_get_serial_sequence('public.infiltrado_resultados', 'id');
    if sequence_name is not null then
        execute format('grant usage, select on sequence %s to authenticated', sequence_name);
    end if;
end;
$$;

drop policy if exists "Infiltrado hosts manage online results" on public.infiltrado_resultados;
create policy "Infiltrado hosts manage online results"
on public.infiltrado_resultados for all to authenticated
using (exists (
    select 1 from public.infiltrado_partidas p
    where p.id = partida_id and p.user_id = auth.uid() and public.can_use_infiltrado()
))
with check (exists (
    select 1 from public.infiltrado_partidas p
    where p.id = partida_id and p.user_id = auth.uid() and public.can_use_infiltrado()
));

create or replace function public.infiltrado_online_create(p_nombre text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_codigo text;
    v_partida_id uuid;
    v_token text := gen_random_uuid()::text;
    v_intentos integer := 0;
begin
    if auth.uid() is null or not public.can_use_infiltrado() then
        return jsonb_build_object('ok', false, 'message', 'Debes iniciar sesión para crear una partida.');
    end if;

    if length(trim(p_nombre)) < 2 then
        return jsonb_build_object('ok', false, 'message', 'El nombre debe tener al menos 2 caracteres.');
    end if;

    loop
        v_codigo := lpad(floor(random() * 1000)::integer::text, 3, '0');
        exit when not exists (
            select 1 from public.infiltrado_partidas where codigo_publico = v_codigo
        );
        v_intentos := v_intentos + 1;
        if v_intentos >= 100 then
            return jsonb_build_object('ok', false, 'message', 'No hay códigos disponibles. Inténtalo de nuevo.');
        end if;
    end loop;

    insert into public.infiltrado_partidas (
        user_id, numero_jugadores, numero_infiltrados, tipo_palabra, palabra_oculta,
        fase, jugador_actual, modo, codigo_publico, estado_online
    )
    values (
        auth.uid(), 3, 1, 'Aleatoria', '', 'CONFIGURACION', 0, 'online', v_codigo, 'waiting'
    )
    returning id into v_partida_id;

    insert into public.infiltrado_jugadores (
        partida_id, nombre, infiltrado, orden, player_token, es_anfitrion
    )
    values (v_partida_id, trim(p_nombre), false, 0, v_token, true);

    return jsonb_build_object(
        'ok', true,
        'partida_id', v_partida_id,
        'codigo_publico', v_codigo,
        'player_token', v_token
    );
end;
$$;

create or replace function public.infiltrado_online_join(p_codigo text, p_nombre text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_partida public.infiltrado_partidas%rowtype;
    v_token text := gen_random_uuid()::text;
    v_orden integer;
begin
    select * into v_partida
    from public.infiltrado_partidas
    where codigo_publico = trim(p_codigo) and modo = 'online';

    if not found then
        return jsonb_build_object('ok', false, 'message', 'La partida no existe.');
    end if;

    if v_partida.estado_online = 'started' then
        return jsonb_build_object('ok', false, 'message', 'La partida ya ha comenzado.');
    end if;

    if length(trim(p_nombre)) < 2 then
        return jsonb_build_object('ok', false, 'message', 'El nombre debe tener al menos 2 caracteres.');
    end if;

    if exists (
        select 1 from public.infiltrado_jugadores
        where partida_id = v_partida.id and lower(nombre) = lower(trim(p_nombre))
    ) then
        return jsonb_build_object('ok', false, 'message', 'Ese nombre ya está utilizado en la partida.');
    end if;

    if (select count(*) from public.infiltrado_jugadores where partida_id = v_partida.id) >= 20 then
        return jsonb_build_object('ok', false, 'message', 'La partida ya tiene el máximo de 20 jugadores.');
    end if;

    select coalesce(max(orden), -1) + 1 into v_orden
    from public.infiltrado_jugadores
    where partida_id = v_partida.id;

    insert into public.infiltrado_jugadores (
        partida_id, nombre, infiltrado, orden, player_token, es_anfitrion
    )
    values (v_partida.id, trim(p_nombre), false, v_orden, v_token, false);

    return jsonb_build_object('ok', true, 'partida_id', v_partida.id, 'player_token', v_token);
end;
$$;

create or replace function public.infiltrado_online_state(p_codigo text, p_player_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_partida public.infiltrado_partidas%rowtype;
    v_jugador public.infiltrado_jugadores%rowtype;
    v_jugadores jsonb;
    v_resultado jsonb;
    v_infiltrados jsonb;
begin
    select * into v_partida
    from public.infiltrado_partidas
    where codigo_publico = trim(p_codigo) and modo = 'online';

    if not found then
        return jsonb_build_object('ok', false, 'message', 'La partida no existe.');
    end if;

    select * into v_jugador
    from public.infiltrado_jugadores
    where partida_id = v_partida.id and player_token = p_player_token;

    if not found then
        return jsonb_build_object('ok', false, 'message', 'El acceso a esta partida ya no es válido.');
    end if;

    -- Limitar las escrituras de presencia evita bucles de eventos Realtime.
    update public.infiltrado_jugadores
    set last_seen_at = now()
    where id = v_jugador.id and last_seen_at < now() - interval '20 seconds';

    select coalesce(jsonb_agg(jsonb_build_object(
        'id', j.id,
        'nombre', j.nombre,
        'es_anfitrion', j.es_anfitrion,
        'last_seen_at', j.last_seen_at
    ) order by j.orden), '[]'::jsonb)
    into v_jugadores
    from public.infiltrado_jugadores j
    where j.partida_id = v_partida.id;

    if v_partida.estado_online = 'finished' then
        select coalesce(jsonb_agg(j.nombre order by j.orden), '[]'::jsonb)
        into v_infiltrados
        from public.infiltrado_jugadores j
        where j.partida_id = v_partida.id and j.infiltrado;

        select jsonb_build_object(
            'acierto', r.acierto,
            'seleccionados', to_jsonb(array_remove(array[j1.nombre, j2.nombre], null)),
            'infiltrados_reales', v_infiltrados
        )
        into v_resultado
        from public.infiltrado_resultados r
        left join public.infiltrado_jugadores j1 on j1.id = r.jugador_sospechoso_1
        left join public.infiltrado_jugadores j2 on j2.id = r.jugador_sospechoso_2
        where r.partida_id = v_partida.id
        order by r.created_at desc
        limit 1;
    end if;

    return jsonb_build_object(
        'ok', true,
        'partida_id', v_partida.id,
        'codigo_publico', v_partida.codigo_publico,
        'estado_online', v_partida.estado_online,
        'numero_infiltrados', v_partida.numero_infiltrados,
        'tipo_palabra', v_partida.tipo_palabra,
        'nombre_jugador', v_jugador.nombre,
        'jugador_nuevo_tras_final', coalesce(v_partida.ended_at is not null and v_jugador.created_at > v_partida.ended_at, false),
        'es_anfitrion', coalesce(
            v_jugador.es_anfitrion and auth.uid() = v_partida.user_id and public.can_use_infiltrado(),
            false
        ),
        'rol', case when v_partida.estado_online = 'started' and v_jugador.infiltrado then 'infiltrado'
                    when v_partida.estado_online = 'started' then 'normal'
                    else null end,
        'palabra_oculta', case when v_partida.estado_online = 'finished' or
                                    (v_partida.estado_online = 'started' and not v_jugador.infiltrado)
                               then v_partida.palabra_oculta else null end,
        'jugadores', v_jugadores,
        'resultado', v_resultado
    );
end;
$$;

create or replace function public.infiltrado_online_start(
    p_partida_id uuid,
    p_player_token text,
    p_numero_infiltrados integer,
    p_tipo_palabra text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_partida public.infiltrado_partidas%rowtype;
    v_total integer;
    v_palabra text;
begin
    select * into v_partida
    from public.infiltrado_partidas
    where id = p_partida_id
      and modo = 'online'
      and user_id = auth.uid()
      and estado_online in ('waiting', 'finished');

    if not found or not public.can_use_infiltrado() or not exists (
        select 1 from public.infiltrado_jugadores
        where partida_id = p_partida_id and player_token = p_player_token and es_anfitrion
    ) then
        return jsonb_build_object('ok', false, 'message', 'Solo el anfitrión puede iniciar la partida.');
    end if;

    select count(*) into v_total from public.infiltrado_jugadores where partida_id = p_partida_id;
    if v_total < 3 then
        return jsonb_build_object('ok', false, 'message', 'Se necesitan al menos 3 jugadores.');
    end if;
    if p_numero_infiltrados < 1 or p_numero_infiltrados >= v_total or p_numero_infiltrados > 2 then
        return jsonb_build_object('ok', false, 'message', 'El número de infiltrados no es válido.');
    end if;

    select w.palabra into v_palabra
    from public.infiltrado_palabras w
    where (p_tipo_palabra = 'Aleatoria' or w.tipo = p_tipo_palabra)
      and not exists (
          select 1 from public.infiltrado_palabras_usadas u
          where u.partida_id = p_partida_id and u.palabra = w.palabra
      )
    order by random()
    limit 1;

    if v_palabra is null then
        return jsonb_build_object('ok', false, 'message', 'Ya se han usado todas las palabras disponibles para este tipo.');
    end if;

    update public.infiltrado_jugadores set infiltrado = false where partida_id = p_partida_id;
    update public.infiltrado_jugadores
    set infiltrado = true
    where id in (
        select id from public.infiltrado_jugadores
        where partida_id = p_partida_id
        order by random()
        limit p_numero_infiltrados
    );

    insert into public.infiltrado_palabras_usadas (partida_id, palabra)
    values (p_partida_id, v_palabra)
    on conflict (partida_id, palabra) do nothing;

    update public.infiltrado_partidas
    set numero_jugadores = v_total,
        numero_infiltrados = p_numero_infiltrados,
        tipo_palabra = p_tipo_palabra,
        palabra_oculta = v_palabra,
        estado_online = 'started',
        fase = 'PARTIDA',
        started_at = now(),
        ended_at = null,
        updated_at = now()
    where id = p_partida_id;

    return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.infiltrado_online_finish(
    p_partida_id uuid,
    p_player_token text,
    p_sospechoso_1 bigint,
    p_sospechoso_2 bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_partida public.infiltrado_partidas%rowtype;
    v_reales bigint[];
    v_seleccionados bigint[];
    v_acierto boolean;
begin
    select * into v_partida
    from public.infiltrado_partidas
    where id = p_partida_id and modo = 'online' and user_id = auth.uid() and estado_online = 'started';

    if not found or not public.can_use_infiltrado() or not exists (
        select 1 from public.infiltrado_jugadores
        where partida_id = p_partida_id and player_token = p_player_token and es_anfitrion
    ) then
        return jsonb_build_object('ok', false, 'message', 'Solo el anfitrión puede finalizar la partida.');
    end if;

    if (v_partida.numero_infiltrados = 2 and (p_sospechoso_2 is null or p_sospechoso_1 = p_sospechoso_2))
       or (v_partida.numero_infiltrados = 1 and p_sospechoso_2 is not null) then
        return jsonb_build_object('ok', false, 'message', 'Selecciona una persona distinta por cada infiltrado.');
    end if;

    if not exists (
        select 1 from public.infiltrado_jugadores where id = p_sospechoso_1 and partida_id = p_partida_id
    ) or (p_sospechoso_2 is not null and not exists (
        select 1 from public.infiltrado_jugadores where id = p_sospechoso_2 and partida_id = p_partida_id
    )) then
        return jsonb_build_object('ok', false, 'message', 'La selección no pertenece a esta partida.');
    end if;

    select array_agg(id order by id) into v_reales
    from public.infiltrado_jugadores
    where partida_id = p_partida_id and infiltrado;

    select array_agg(valor order by valor) into v_seleccionados
    from unnest(array_remove(array[p_sospechoso_1, p_sospechoso_2], null)) as valor;

    v_acierto := v_reales = v_seleccionados;

    insert into public.infiltrado_resultados (
        partida_id, jugador_sospechoso_1, jugador_sospechoso_2, acierto
    )
    values (p_partida_id, p_sospechoso_1, p_sospechoso_2, v_acierto);

    delete from public.infiltrado_palabras_usadas where partida_id = p_partida_id;

    update public.infiltrado_partidas
    set estado_online = 'finished', fase = 'FINALIZADA', ended_at = now(), updated_at = now()
    where id = p_partida_id;

    return jsonb_build_object('ok', true, 'acierto', v_acierto);
end;
$$;

create or replace function public.infiltrado_online_remove_player(
    p_partida_id uuid,
    p_player_token text,
    p_jugador_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
    if auth.uid() is null or not public.can_use_infiltrado() or not exists (
        select 1 from public.infiltrado_partidas p
        join public.infiltrado_jugadores j on j.partida_id = p.id
        where p.id = p_partida_id
          and p.user_id = auth.uid()
          and p.estado_online <> 'started'
          and j.player_token = p_player_token
          and j.es_anfitrion
    ) then
        return jsonb_build_object('ok', false, 'message', 'No puedes eliminar jugadores en este momento.');
    end if;

    delete from public.infiltrado_jugadores
    where id = p_jugador_id and partida_id = p_partida_id and not es_anfitrion;

    return jsonb_build_object('ok', true);
end;
$$;

revoke all on function public.infiltrado_online_create(text) from public;
revoke all on function public.infiltrado_online_join(text, text) from public;
revoke all on function public.infiltrado_online_state(text, text) from public;
revoke all on function public.infiltrado_online_start(uuid, text, integer, text) from public;
revoke all on function public.infiltrado_online_finish(uuid, text, bigint, bigint) from public;
revoke all on function public.infiltrado_online_remove_player(uuid, text, bigint) from public;

grant execute on function public.infiltrado_online_create(text) to authenticated;
grant execute on function public.infiltrado_online_join(text, text) to anon, authenticated;
grant execute on function public.infiltrado_online_state(text, text) to anon, authenticated;
grant execute on function public.infiltrado_online_start(uuid, text, integer, text) to authenticated;
grant execute on function public.infiltrado_online_finish(uuid, text, bigint, bigint) to authenticated;
grant execute on function public.infiltrado_online_remove_player(uuid, text, bigint) to authenticated;

-- Realtime se habilita para anfitriones autenticados; los invitados conservan actualización manual.
do $$
begin
    if not exists (
        select 1 from pg_publication_tables
        where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'infiltrado_partidas'
    ) then
        alter publication supabase_realtime add table public.infiltrado_partidas;
    end if;

    if not exists (
        select 1 from pg_publication_tables
        where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'infiltrado_jugadores'
    ) then
        alter publication supabase_realtime add table public.infiltrado_jugadores;
    end if;
end;
$$;
