insert into public.app_projects (slug, name, description)
values ('infiltrado', 'infiltrado', 'Juego social de roles ocultos.')
on conflict (slug) do update
set name = excluded.name,
    description = excluded.description,
    is_active = true,
    updated_at = now();

create or replace function public.can_use_infiltrado()
returns boolean
language sql
security definer
set search_path = public
as $$
    select public.is_admin()
        or exists (
            select 1
            from public.project_members pm
            join public.app_projects ap on ap.id = pm.project_id
            where pm.user_id = auth.uid()
              and ap.slug = 'infiltrado'
              and ap.is_active
        );
$$;

create table if not exists public.infiltrado_palabras (
    id bigint generated by default as identity primary key,
    tipo text not null,
    palabra text not null,
    created_at timestamptz not null default now(),
    unique (tipo, palabra)
);

create table if not exists public.infiltrado_partidas (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
    numero_jugadores integer not null check (numero_jugadores between 3 and 20),
    numero_infiltrados integer not null check (numero_infiltrados between 1 and 2),
    tipo_palabra text not null,
    palabra_oculta text not null,
    fase text not null default 'REPARTO',
    jugador_actual integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id)
);

alter table public.infiltrado_partidas alter column user_id set default auth.uid();

create table if not exists public.infiltrado_jugadores (
    id bigint generated by default as identity primary key,
    partida_id uuid not null references public.infiltrado_partidas(id) on delete cascade,
    nombre text not null,
    infiltrado boolean not null default false,
    orden integer not null,
    created_at timestamptz not null default now(),
    unique (partida_id, orden)
);

alter table public.infiltrado_palabras enable row level security;
alter table public.infiltrado_partidas enable row level security;
alter table public.infiltrado_jugadores enable row level security;

grant select on public.infiltrado_palabras to authenticated;
grant select, insert, update, delete on public.infiltrado_partidas to authenticated;
grant select, insert, update, delete on public.infiltrado_jugadores to authenticated;

do $$
declare
    sequence_name text;
begin
    foreach sequence_name in array array[
        pg_get_serial_sequence('public.infiltrado_palabras', 'id'),
        pg_get_serial_sequence('public.infiltrado_jugadores', 'id')
    ]
    loop
        if sequence_name is not null then
            execute format('grant usage, select on sequence %s to authenticated', sequence_name);
        end if;
    end loop;
end;
$$;

drop policy if exists "Infiltrado users can read words" on public.infiltrado_palabras;
drop policy if exists "Infiltrado users manage own games" on public.infiltrado_partidas;
drop policy if exists "Infiltrado users read own players" on public.infiltrado_jugadores;
drop policy if exists "Infiltrado users insert own players" on public.infiltrado_jugadores;
drop policy if exists "Infiltrado users update own players" on public.infiltrado_jugadores;
drop policy if exists "Infiltrado users delete own players" on public.infiltrado_jugadores;

create policy "Infiltrado users can read words"
on public.infiltrado_palabras for select to authenticated
using (public.can_use_infiltrado());

create policy "Infiltrado users manage own games"
on public.infiltrado_partidas for all to authenticated
using (user_id = auth.uid() and public.can_use_infiltrado())
with check (user_id = auth.uid() and public.can_use_infiltrado());

create policy "Infiltrado users read own players"
on public.infiltrado_jugadores for select to authenticated
using (exists (
    select 1 from public.infiltrado_partidas p
    where p.id = partida_id and p.user_id = auth.uid() and public.can_use_infiltrado()
));

create policy "Infiltrado users insert own players"
on public.infiltrado_jugadores for insert to authenticated
with check (exists (
    select 1 from public.infiltrado_partidas p
    where p.id = partida_id and p.user_id = auth.uid() and public.can_use_infiltrado()
));

create policy "Infiltrado users update own players"
on public.infiltrado_jugadores for update to authenticated
using (exists (
    select 1 from public.infiltrado_partidas p
    where p.id = partida_id and p.user_id = auth.uid() and public.can_use_infiltrado()
));

create policy "Infiltrado users delete own players"
on public.infiltrado_jugadores for delete to authenticated
using (exists (
    select 1 from public.infiltrado_partidas p
    where p.id = partida_id and p.user_id = auth.uid() and public.can_use_infiltrado()
));

insert into public.infiltrado_palabras (tipo, palabra)
select 'Lugares', palabra from unnest(array[
    'Banco','Puerto','Plaza','Canal','Puente','Torre','Sierra','Fuente','Mina','Estación','Terminal','Refugio','Mercado','Parque','Jardín','Castillo','Muralla','Palacio','Cueva','Desierto','Oasis','Costa','Bahía','Cabo','Isla','Volcán','Laguna','Río','Delta','Valle','Pico','Mirador','Túnel','Paso','Cruce','Frontera','Aeropuerto','Acuario','Zoológico','Biblioteca','Archivo','Ayuntamiento','Embajada','Teatro','Auditorio','Estadio','Circuito','Hipódromo','Camping','Balneario','Santuario','Monasterio','Ermita','Catedral','Hospital','Clínica','Laboratorio','Observatorio','Faro','Astillero','Invernadero','Granja','Viñedo','Bodega','Almacén','Fábrica','Central','Depósito','Gasolinera','Taller','Garaje','Patio','Azotea','Sótano','Desván','Pasillo','Vestíbulo','Andén','Muelle','Dársena','Rotonda','Avenida','Callejón','Boulevard','Glorieta','Paseo','Escenario','Camerino','Trinchera','Campamento','Cuartel','Fortaleza','Pradera','Pantano','Embalse','Acantilado','Bosque','Prisión','Mercado central','Puerto pesquero'
]) as palabra on conflict (tipo, palabra) do nothing;

insert into public.infiltrado_palabras (tipo, palabra)
select 'Cosas', palabra from unnest(array[
    'Sirena','Gato','Sierra','Ratón','Bota','Corona','Cadena','Pluma','Vela','Copa','Llave','Banco','Hoja','Red','Lima','Mango','Bomba','Piloto','Muelle','Perla','Estrella','Cometa','Ancla','Aguja','Escudo','Máscara','Campana','Reloj','Ficha','Dado','Carta','Disco','Cuerda','Globo','Tronco','Tabla','Tecla','Portal','Pantalla','Lente','Casco','Mando','Torre','Foco','Pinza','Goma','Cepillo','Tornillo','Tuerca','Imán','Espejo','Ventana','Candado','Cofre','Sello','Timbre','Flecha','Arco','Nudo','Jaula','Caja','Maleta','Paraguas','Bastón','Medalla','Trofeo','Silbato','Brújula','Linterna','Botón','Engranaje','Martillo','Yunque','Molino','Campanilla','Hélice','Barril','Bidón','Cáliz','Antorcha','Trompeta','Tambor','Violín','Flauta','Acordeón','Cámara','Micrófono','Altavoz','Radar','Satélite','Mapa','Pergamino','Diario','Collar','Sortija','Amuleto','Radio','Sello postal','Bandera'
]) as palabra on conflict (tipo, palabra) do nothing;

insert into public.infiltrado_palabras (tipo, palabra)
select 'Profesiones', palabra from unnest(array[
    'Cocinero','Pintor','Constructor','Jardinero','Cartero','Médico','Enfermero','Bombero','Policía','Juez','Abogado','Profesor','Bibliotecario','Actor','Cantante','Músico','Director','Fotógrafo','Periodista','Escritor','Editor','Traductor','Programador','Diseñador','Arquitecto','Ingeniero','Albañil','Carpintero','Fontanero','Electricista','Mecánico','Soldador','Joyero','Sastre','Zapatero','Panadero','Pastelero','Carnicero','Pescadero','Agricultor','Ganadero','Veterinario','Apicultor','Astrónomo','Científico','Químico','Biólogo','Geólogo','Piloto','Navegante','Marinero','Capitán','Azafato','Guía','Recepcionista','Camarero','Sumiller','Mago','Payaso','Locutor','Presentador','DJ','Entrenador','Árbitro','Futbolista','Ciclista','Nadador','Boxeador','Detective','Espía','Guardabosques','Minero','Buzo','Rescatador','Explorador','Cazador','Leñador','Taxista','Conductor','Repartidor','Mensajero','Comerciante','Vendedor','Cajero','Banquero','Corredor','Notario','Diplomático','Embajador','Sacerdote','Monje','Cerrajero','Relojero','Barbero','Peluquero','Estilista','Influencer','Actor de doblaje','Community Manager','Locomotorista'
]) as palabra on conflict (tipo, palabra) do nothing;
