create table if not exists public.infiltrado_palabras_usadas (
    id bigint generated by default as identity primary key,
    partida_id uuid not null references public.infiltrado_partidas(id) on delete cascade,
    palabra text not null,
    created_at timestamptz not null default now(),
    unique (partida_id, palabra)
);

alter table public.infiltrado_palabras_usadas enable row level security;

grant select, insert, delete on public.infiltrado_palabras_usadas to authenticated;

do $$
declare
    sequence_name text;
begin
    sequence_name := pg_get_serial_sequence('public.infiltrado_palabras_usadas', 'id');
    if sequence_name is not null then
        execute format('grant usage, select on sequence %s to authenticated', sequence_name);
    end if;
end;
$$;

drop policy if exists "Infiltrado users read own used words" on public.infiltrado_palabras_usadas;
drop policy if exists "Infiltrado users insert own used words" on public.infiltrado_palabras_usadas;
drop policy if exists "Infiltrado users delete own used words" on public.infiltrado_palabras_usadas;

create policy "Infiltrado users read own used words"
on public.infiltrado_palabras_usadas for select to authenticated
using (exists (
    select 1 from public.infiltrado_partidas p
    where p.id = partida_id and p.user_id = auth.uid() and public.can_use_infiltrado()
));

create policy "Infiltrado users insert own used words"
on public.infiltrado_palabras_usadas for insert to authenticated
with check (exists (
    select 1 from public.infiltrado_partidas p
    where p.id = partida_id and p.user_id = auth.uid() and public.can_use_infiltrado()
));

create policy "Infiltrado users delete own used words"
on public.infiltrado_palabras_usadas for delete to authenticated
using (exists (
    select 1 from public.infiltrado_partidas p
    where p.id = partida_id and p.user_id = auth.uid() and public.can_use_infiltrado()
));

insert into public.infiltrado_palabras_usadas (partida_id, palabra)
select id, palabra_oculta
from public.infiltrado_partidas
on conflict (partida_id, palabra) do nothing;
