-- Nueva estructura de Trastero basada en carpetas e items.
-- AVISO: esta migracion sustituye las tablas antiguas de espacios/zonas/cajas/objetos.

begin;

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles
    add constraint profiles_role_check check (role in ('admin', 'member', 'viewer', 'trastero'));

create or replace function public.can_access_trastero()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid()
          and role = 'admin'
    );
$$;

grant execute on function public.can_access_trastero() to authenticated;

drop table if exists public.trastero_objetos cascade;
drop table if exists public.trastero_cajas cascade;
drop table if exists public.trastero_zonas cascade;
drop table if exists public.trastero_espacios cascade;
drop table if exists public.trastero_fotos cascade;

create table public.trastero_carpetas (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    parent_id bigint null references public.trastero_carpetas(id) on delete cascade,
    nombre text not null,
    codigo text null,
    notas text null,
    created_at timestamptz not null default now(),
    updated_at timestamptz
);

create table public.trastero_items (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    carpeta_id bigint null references public.trastero_carpetas(id) on delete set null,
    nombre text not null,
    codigo text null,
    cantidad numeric null default 1,
    unidad text null default 'unit',
    notas text null,
    created_at timestamptz not null default now(),
    updated_at timestamptz
);

create table public.trastero_fotos (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    tipo text not null check (tipo in ('carpeta', 'item')),
    relacion_id bigint not null,
    storage_path text not null unique,
    es_portada boolean not null default false,
    created_at timestamptz not null default now()
);

create index trastero_carpetas_user_id_idx on public.trastero_carpetas(user_id);
create index trastero_carpetas_parent_id_idx on public.trastero_carpetas(parent_id);
create index trastero_carpetas_nombre_idx on public.trastero_carpetas using gin (to_tsvector('simple', coalesce(nombre, '') || ' ' || coalesce(codigo, '') || ' ' || coalesce(notas, '')));
create index trastero_items_user_id_idx on public.trastero_items(user_id);
create index trastero_items_carpeta_id_idx on public.trastero_items(carpeta_id);
create index trastero_items_nombre_idx on public.trastero_items using gin (to_tsvector('simple', coalesce(nombre, '') || ' ' || coalesce(codigo, '') || ' ' || coalesce(notas, '')));
create index trastero_fotos_user_id_idx on public.trastero_fotos(user_id);
create index trastero_fotos_tipo_relacion_idx on public.trastero_fotos(tipo, relacion_id);
create index trastero_fotos_portada_idx on public.trastero_fotos(tipo, relacion_id, es_portada);

create or replace function public.trastero_set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trastero_carpetas_updated_at on public.trastero_carpetas;
create trigger trastero_carpetas_updated_at
before update on public.trastero_carpetas
for each row execute function public.trastero_set_updated_at();

drop trigger if exists trastero_items_updated_at on public.trastero_items;
create trigger trastero_items_updated_at
before update on public.trastero_items
for each row execute function public.trastero_set_updated_at();

create or replace function public.trastero_validate_folder()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    if new.user_id <> auth.uid() and auth.uid() is not null then
        raise exception 'user_id no permitido';
    end if;
    if new.parent_id is not null and not exists (
        select 1 from public.trastero_carpetas
        where id = new.parent_id and user_id = new.user_id
    ) then
        raise exception 'Carpeta padre no permitida';
    end if;
    return new;
end;
$$;

create or replace function public.trastero_validate_item()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    if new.user_id <> auth.uid() and auth.uid() is not null then
        raise exception 'user_id no permitido';
    end if;
    if new.carpeta_id is not null and not exists (
        select 1 from public.trastero_carpetas
        where id = new.carpeta_id and user_id = new.user_id
    ) then
        raise exception 'Carpeta no permitida';
    end if;
    return new;
end;
$$;

create or replace function public.trastero_validate_photo()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    if new.user_id <> auth.uid() and auth.uid() is not null then
        raise exception 'user_id no permitido';
    end if;
    if new.tipo = 'carpeta' and not exists (
        select 1 from public.trastero_carpetas where id = new.relacion_id and user_id = new.user_id
    ) then
        raise exception 'Carpeta no permitida';
    end if;
    if new.tipo = 'item' and not exists (
        select 1 from public.trastero_items where id = new.relacion_id and user_id = new.user_id
    ) then
        raise exception 'Item no permitido';
    end if;
    return new;
end;
$$;

create trigger trastero_carpetas_validate before insert or update on public.trastero_carpetas
for each row execute function public.trastero_validate_folder();
create trigger trastero_items_validate before insert or update on public.trastero_items
for each row execute function public.trastero_validate_item();
create trigger trastero_fotos_validate before insert or update on public.trastero_fotos
for each row execute function public.trastero_validate_photo();

alter table public.trastero_carpetas enable row level security;
alter table public.trastero_items enable row level security;
alter table public.trastero_fotos enable row level security;

create policy "Trastero own folders" on public.trastero_carpetas
for all to authenticated
using (public.can_access_trastero() and auth.uid() = user_id)
with check (public.can_access_trastero() and auth.uid() = user_id);

create policy "Trastero own items" on public.trastero_items
for all to authenticated
using (public.can_access_trastero() and auth.uid() = user_id)
with check (public.can_access_trastero() and auth.uid() = user_id);

create policy "Trastero own photos" on public.trastero_fotos
for all to authenticated
using (public.can_access_trastero() and auth.uid() = user_id)
with check (public.can_access_trastero() and auth.uid() = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('trastero-fotos', 'trastero-fotos', false, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif'])
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Trastero users read own photos" on storage.objects;
create policy "Trastero users read own photos" on storage.objects for select to authenticated
using (bucket_id = 'trastero-fotos' and public.can_access_trastero() and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "Trastero users upload own photos" on storage.objects;
create policy "Trastero users upload own photos" on storage.objects for insert to authenticated
with check (bucket_id = 'trastero-fotos' and public.can_access_trastero() and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "Trastero users update own photos" on storage.objects;
create policy "Trastero users update own photos" on storage.objects for update to authenticated
using (bucket_id = 'trastero-fotos' and public.can_access_trastero() and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id = 'trastero-fotos' and public.can_access_trastero() and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "Trastero users delete own photos" on storage.objects;
create policy "Trastero users delete own photos" on storage.objects for delete to authenticated
using (bucket_id = 'trastero-fotos' and public.can_access_trastero() and (storage.foldername(name))[1] = auth.uid()::text);

insert into public.app_projects (slug, name, description)
values ('trastero', 'Trastero', 'Inventario privado por carpetas e items.')
on conflict (slug) do update
set name = excluded.name,
    description = excluded.description,
    is_active = true;

commit;
