insert into public.app_projects (slug, name, description)
values ('bingo', 'bingo', 'Gestion del monitor y las partidas de Bingo.')
on conflict (slug) do update
set name = excluded.name,
    description = excluded.description,
    is_active = true,
    updated_at = now();

create or replace function public.can_manage_bingo()
returns boolean
language sql
security definer
set search_path = public
as $$
    select public.is_admin()
        or exists (
            select 1
            from public.project_members pm
            join public.app_projects ap on ap.id = pm.project_id
            where pm.user_id = auth.uid()
              and ap.slug = 'bingo'
              and ap.is_active
              and pm.role in ('owner', 'editor')
        );
$$;

create table public.bingo_partidas (
    id integer generated by default as identity (start with 100 increment by 1),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    iniciada boolean not null default false,
    primary key (id),
    constraint bingo_partidas_id_tres_cifras check (id between 100 and 999)
);

alter sequence public.bingo_partidas_id_seq minvalue 100 maxvalue 999 no cycle;

alter table public.bingo_partidas enable row level security;

grant select on public.bingo_partidas to anon, authenticated;
grant insert, update, delete on public.bingo_partidas to authenticated;
grant usage, select on sequence public.bingo_partidas_id_seq to authenticated;

create policy "Public can read bingo partidas"
on public.bingo_partidas
for select
to anon, authenticated
using (true);

create policy "Bingo managers can insert partidas"
on public.bingo_partidas
for insert
to authenticated
with check (public.can_manage_bingo());

create policy "Bingo managers can update partidas"
on public.bingo_partidas
for update
to authenticated
using (public.can_manage_bingo())
with check (public.can_manage_bingo());

create policy "Bingo managers can delete partidas"
on public.bingo_partidas
for delete
to authenticated
using (public.can_manage_bingo());

-- Supabase Auth necesita un email aunque la interfaz use el alias "demobingo".
-- Tras crear demobingo@alaraz1921.com en Authentication, ejecutar este bloque
-- para asignarle acceso de editor al proyecto Bingo.
insert into public.project_members (project_id, user_id, role)
select ap.id, au.id, 'editor'
from public.app_projects ap
join auth.users au on lower(au.email) = 'demobingo@alaraz1921.com'
where ap.slug = 'bingo'
on conflict (project_id, user_id) do update set role = excluded.role;
